name: Install build prerequisites

inputs:
  os:
    description: The operating system on which the test is being run
    required: true
  crypto:
    description: The crypto library being used
    required: true
  cache-dir:  
    description: Where to put vcpkg cache
    required: true

runs:
  using: "composite"
  steps:
    - name: Capture vcpkg revision for use in cache key
      shell: bash
      run: |
        git -C vcpkg rev-parse HEAD > vcpkg_commit.txt

    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.cache-dir }}
        key: v02-vcpkg-${{ inputs.os }}-${{ inputs.crypto }}-${{ hashFiles('vcpkg_commit.txt', 'alternatives/*/vcpkg.json') }}
        restore-keys: |
          v02-vcpkg-${{ inputs.os }}-${{ inputs.crypto }}

    - name: Install dependencies (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        brew install llvm pkg-config nasm go
        ln -s "/usr/local/opt/llvm/bin/clang-format" "/usr/local/bin/clang-format"
        ln -s "/usr/local/opt/llvm/bin/clang-tidy" "/usr/local/bin/clang-tidy"

    - name: Install dependencies (Ubuntu)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt-get install -y linux-headers-$(uname -r) nasm
