add_test( [==[AEAD Known-Answer]==] D:/work/github/mlspp/build/lib/hpke/test/hpke_test.exe [==[--test-case=AEAD Known-Answer]==])
set_tests_properties( [==[AEAD Known-Answer]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/lib/hpke/test)
add_test( [==[AEAD Round-Trip]==] D:/work/github/mlspp/build/lib/hpke/test/hpke_test.exe [==[--test-case=AEAD Round-Trip]==])
set_tests_properties( [==[AEAD Round-Trip]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/lib/hpke/test)
add_test( [==[Certificate Known-Answer depth 2]==] D:/work/github/mlspp/build/lib/hpke/test/hpke_test.exe [==[--test-case=Certificate Known-Answer depth 2]==])
set_tests_properties( [==[Certificate Known-Answer depth 2]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/lib/hpke/test)
add_test( [==[Certificate Known-Answer depth 2 with SKID/ADID]==] D:/work/github/mlspp/build/lib/hpke/test/hpke_test.exe [==[--test-case=Certificate Known-Answer depth 2 with SKID/ADID]==])
set_tests_properties( [==[Certificate Known-Answer depth 2 with SKID/ADID]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/lib/hpke/test)
add_test( [==[Certificate Known-Answer depth 2 with SAN RFC822Name]==] D:/work/github/mlspp/build/lib/hpke/test/hpke_test.exe [==[--test-case=Certificate Known-Answer depth 2 with SAN RFC822Name]==])
set_tests_properties( [==[Certificate Known-Answer depth 2 with SAN RFC822Name]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/lib/hpke/test)
add_test( [==[HPKE Test Vectors]==] D:/work/github/mlspp/build/lib/hpke/test/hpke_test.exe [==[--test-case=HPKE Test Vectors]==])
set_tests_properties( [==[HPKE Test Vectors]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/lib/hpke/test)
add_test( [==[HPKE Round-Trip]==] D:/work/github/mlspp/build/lib/hpke/test/hpke_test.exe [==[--test-case=HPKE Round-Trip]==])
set_tests_properties( [==[HPKE Round-Trip]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/lib/hpke/test)
add_test( [==[KDF Known-Answer]==] D:/work/github/mlspp/build/lib/hpke/test/hpke_test.exe [==[--test-case=KDF Known-Answer]==])
set_tests_properties( [==[KDF Known-Answer]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/lib/hpke/test)
add_test( [==[KEM round-trip]==] D:/work/github/mlspp/build/lib/hpke/test/hpke_test.exe [==[--test-case=KEM round-trip]==])
set_tests_properties( [==[KEM round-trip]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/lib/hpke/test)
add_test( [==[Random bytes]==] D:/work/github/mlspp/build/lib/hpke/test/hpke_test.exe [==[--test-case=Random bytes]==])
set_tests_properties( [==[Random bytes]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/lib/hpke/test)
add_test( [==[Signature Known-Answer]==] D:/work/github/mlspp/build/lib/hpke/test/hpke_test.exe [==[--test-case=Signature Known-Answer]==])
set_tests_properties( [==[Signature Known-Answer]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/lib/hpke/test)
add_test( [==[Signature Round-Trip]==] D:/work/github/mlspp/build/lib/hpke/test/hpke_test.exe [==[--test-case=Signature Round-Trip]==])
set_tests_properties( [==[Signature Round-Trip]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/lib/hpke/test)
set( hpke_test_TESTS [==[AEAD Known-Answer]==] [==[AEAD Round-Trip]==] [==[Certificate Known-Answer depth 2]==] [==[Certificate Known-Answer depth 2 with SKID/ADID]==] [==[Certificate Known-Answer depth 2 with SAN RFC822Name]==] [==[HPKE Test Vectors]==] [==[HPKE Round-Trip]==] [==[KDF Known-Answer]==] [==[KEM round-trip]==] [==[Random bytes]==] [==[Signature Known-Answer]==] [==[Signature Round-Trip]==])
