add_test( [==[Basic Credential]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Basic Credential]==])
set_tests_properties( [==[Basic Credential]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[X509 Credential Depth 2]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=X509 Credential Depth 2]==])
set_tests_properties( [==[X509 Credential Depth 2]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[X509 Credential Depth 2 Marshal/Unmarshal]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=X509 Credential Depth 2 Marshal/Unmarshal]==])
set_tests_properties( [==[X509 Credential Depth 2 Marshal/Unmarshal]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[X509 Credential Depth 1 Marshal/Unmarshal]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=X509 Credential Depth 1 Marshal/Unmarshal]==])
set_tests_properties( [==[X509 Credential Depth 1 Marshal/Unmarshal]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Crypto Interop]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Crypto Interop]==])
set_tests_properties( [==[Crypto Interop]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Basic HPKE]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Basic HPKE]==])
set_tests_properties( [==[Basic HPKE]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[HPKE Key Serialization]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=HPKE Key Serialization]==])
set_tests_properties( [==[HPKE Key Serialization]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Basic Signature]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Basic Signature]==])
set_tests_properties( [==[Basic Signature]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Signature Key Serializion]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Signature Key Serializion]==])
set_tests_properties( [==[Signature Key Serializion]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Hash Ratchet Interop]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Hash Ratchet Interop]==])
set_tests_properties( [==[Hash Ratchet Interop]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Key Schedule Interop]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Key Schedule Interop]==])
set_tests_properties( [==[Key Schedule Interop]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( Extensions D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Extensions]==])
set_tests_properties( Extensions PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Messages Interop]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Messages Interop]==])
set_tests_properties( [==[Messages Interop]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Two-Person Session Creation]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Two-Person Session Creation]==])
set_tests_properties( [==[Two-Person Session Creation]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Full-Size Session Creation]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Full-Size Session Creation]==])
set_tests_properties( [==[Full-Size Session Creation]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Update within Session]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Update within Session]==])
set_tests_properties( [==[Update within Session]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Remove within Session]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Remove within Session]==])
set_tests_properties( [==[Remove within Session]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Replace within Session]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Replace within Session]==])
set_tests_properties( [==[Replace within Session]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Full Session Life-Cycle]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Full Session Life-Cycle]==])
set_tests_properties( [==[Full Session Life-Cycle]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Two Person]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Two Person]==])
set_tests_properties( [==[Two Person]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Add Multiple Members]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Add Multiple Members]==])
set_tests_properties( [==[Add Multiple Members]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Full Size Group]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Full Size Group]==])
set_tests_properties( [==[Full Size Group]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Update Everyone via Empty Commit]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Update Everyone via Empty Commit]==])
set_tests_properties( [==[Update Everyone via Empty Commit]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Update Everyone in a Group]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Update Everyone in a Group]==])
set_tests_properties( [==[Update Everyone in a Group]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Remove Members from a Group]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Remove Members from a Group]==])
set_tests_properties( [==[Remove Members from a Group]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Roster Updates]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Roster Updates]==])
set_tests_properties( [==[Roster Updates]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Tree Math]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Tree Math]==])
set_tests_properties( [==[Tree Math]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[ParentNode Equality]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=ParentNode Equality]==])
set_tests_properties( [==[ParentNode Equality]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Node public key]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Node public key]==])
set_tests_properties( [==[Node public key]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[Optional node hashes]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=Optional node hashes]==])
set_tests_properties( [==[Optional node hashes]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[TreeKEM Private Key]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=TreeKEM Private Key]==])
set_tests_properties( [==[TreeKEM Private Key]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[TreeKEM Public Key]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=TreeKEM Public Key]==])
set_tests_properties( [==[TreeKEM Public Key]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[TreeKEM encap/decap]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=TreeKEM encap/decap]==])
set_tests_properties( [==[TreeKEM encap/decap]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
add_test( [==[TreeKEM Interop]==] D:/work/github/mlspp/build/test/mlspp_test.exe [==[--test-case=TreeKEM Interop]==])
set_tests_properties( [==[TreeKEM Interop]==] PROPERTIES WORKING_DIRECTORY D:/work/github/mlspp/build/test)
set( mlspp_test_TESTS [==[Basic Credential]==] [==[X509 Credential Depth 2]==] [==[X509 Credential Depth 2 Marshal/Unmarshal]==] [==[X509 Credential Depth 1 Marshal/Unmarshal]==] [==[Crypto Interop]==] [==[Basic HPKE]==] [==[HPKE Key Serialization]==] [==[Basic Signature]==] [==[Signature Key Serializion]==] [==[Hash Ratchet Interop]==] [==[Key Schedule Interop]==] Extensions [==[Messages Interop]==] [==[Two-Person Session Creation]==] [==[Full-Size Session Creation]==] [==[Update within Session]==] [==[Remove within Session]==] [==[Replace within Session]==] [==[Full Session Life-Cycle]==] [==[Two Person]==] [==[Add Multiple Members]==] [==[Full Size Group]==] [==[Update Everyone via Empty Commit]==] [==[Update Everyone in a Group]==] [==[Remove Members from a Group]==] [==[Roster Updates]==] [==[Tree Math]==] [==[ParentNode Equality]==] [==[Node public key]==] [==[Optional node hashes]==] [==[TreeKEM Private Key]==] [==[TreeKEM Public Key]==] [==[TreeKEM encap/decap]==] [==[TreeKEM Interop]==])
