name: Build for older MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  MACOSX_DEPLOYMENT_TARGET: 10.11

jobs:
  build:
    runs-on: macos-latest
    
    env:
        CMAKE_BUILD_DIR: ${{ github.workspace }}/build
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: dependencies
      run: |
        brew install llvm
        ln -s "/usr/local/opt/llvm/bin/clang-format" "/usr/local/bin/clang-format"
        ln -s "/usr/local/opt/llvm/bin/clang-tidy" "/usr/local/bin/clang-tidy"

    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@v6
      with:
        setupOnly: true
        vcpkgDirectory: '${{ env.VCPKG_INSTALLATION_ROOT }}'
        appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
        additionalCachedPaths: ${{ env.CMAKE_BUILD_DIR }}/vcpkg_installed

    - name: build the library
      run: |
        cmake -B "${{ env.CMAKE_BUILD_DIR }}" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_INSTALLATION_ROOT }}/scripts/buildsystems/vcpkg.cmake" .
        cmake --build "${{ env.CMAKE_BUILD_DIR }}" --target mlspp
