name: Build for older MacOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  MACOSX_DEPLOYMENT_TARGET: 10.11

jobs:
  build:
    runs-on: macos-latest
    
    env:
        CMAKE_BUILD_DIR: ${{ github.workspace }}/build
        TOOLCHAIN_FILE: $VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake
        VCPKG_BINARY_SOURCES: files,${{ github.workspace }}/build/cache,readwrite

    steps:
    - uses: actions/checkout@v3
     
    - name: dependencies
      run: |
        brew install llvm pkg-config
        ln -s "/usr/local/opt/llvm/bin/clang-format" "/usr/local/bin/clang-format"
        ln -s "/usr/local/opt/llvm/bin/clang-tidy" "/usr/local/bin/clang-tidy"

    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/build/cache
        key: ${{ runner.os }}

    - name: build the library
      run: |
        cmake -B "${{ env.CMAKE_BUILD_DIR }}" -DCMAKE_TOOLCHAIN_FILE="${{ env.TOOLCHAIN_FILE }}" .
        cmake --build "${{ env.CMAKE_BUILD_DIR }}" --target mlspp --parallel 2
