name: Test interoperability

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
        CMAKE_BUILD_DIR: ${{ github.workspace }}/build
        TOOLCHAIN_FILE: $VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake

    steps:
    - uses: actions/checkout@v2

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: |
            ${{ env.CMAKE_BUILD_DIR }}/vcpkg_installed
        key: ${{ runner.os }}-${{ hashFiles( '**/vcpkg.json' ) }}

    - name: Build the library      
      run: |
        cmake -B build -DCMAKE_TOOLCHAIN_FILE="${{ env.TOOLCHAIN_FILE }}" .
        cmake --build build          

    - name: Build interop harness
      run: |
        cd cmd/interop
        cmake -B build -DSANITIZERS=ON -DCMAKE_TOOLCHAIN_FILE="${{ env.TOOLCHAIN_FILE }}" .
        cmake --build build

    - name: Test self-interop
      run: |
        make -C cmd/interop self-test

    - name: Test interop on test vectors
      run: |
        make -C cmd/interop interop-test

    - name: Test gRPC live interop with self
      run: |
        cd cmd/interop
        ./grpc-self-test.sh
