name: Test interoperability

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
        CMAKE_BUILD_DIR: ${{ github.workspace }}/build
        TOOLCHAIN_FILE: $VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake
        VCPKG_BINARY_SOURCES: files,${{ github.workspace }}/build/cache,readwrite

    steps:
    - uses: actions/checkout@v3

    - name: dependencies (ubuntu)
      run: |
        apt-get install linux-headers-$(uname -r)

    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/build/cache
        key: ${{ runner.os }}

    - name: Build the library      
      run: |
        cmake -B build -DCMAKE_TOOLCHAIN_FILE="${{ env.TOOLCHAIN_FILE }}" .
        cmake --build build --parallel 2

    - name: Build interop harness
      run: |
        cd cmd/interop
        cmake -B build -DSANITIZERS=ON -DCMAKE_TOOLCHAIN_FILE="${{ env.TOOLCHAIN_FILE }}" .
        cmake --build build --parallel 2

    - name: Test self-interop
      run: |
        make -C cmd/interop self-test

    - name: Test interop on test vectors
      run: |
        make -C cmd/interop interop-test

    - name: Test gRPC live interop with self
      run: |
        cd cmd/interop
        ./grpc-self-test.sh
